service: task-lambda

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev
  environment:
    DYNAMODB_TABLE: task-table-${sls:stage}


package:
  include:
    - dist/**

    


functions:
  getTasks:
    handler: dist/infrastructure/handlers.getTasks
    events:
      - http:
          path: tasks
          method: get

  getTask:
    handler: dist/infrastructure/handlers.getTask
    events:
      - http:
          path: tasks/{id}
          method: get

  createTask:
    handler: dist/infrastructure/handlers.createTask
    events:
      - http:
          path: tasks
          method: post

  updateTask:
    handler: dist/infrastructure/handlers.updateTask
    events:
      - http:
          path: tasks/{id}
          method: put

  deleteTask:
    handler: dist/infrastructure/handlers.deleteTask
    events:
      - http:
          path: tasks/{id}
          method: delete

resources:
  Resources:
    TaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: task-table-${sls:stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST